# https://github.com/marketplace/actions/run-on-architecture
name: Meson Foreign architectures

on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  multiarch:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        include:
          - arch: armv7
            distro: ubuntu_latest  # at 24.04 according to uraimo/run-on-arch-action@v3.0.1
            cxx_flags: -Wno-psabi
          - arch: ppc64le
            distro: ubuntu_latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build and test
      uses: uraimo/run-on-arch-action@v3.0.1
      id: build
      with:
        arch: ${{ matrix.arch }}
        distro: ${{ matrix.distro }}
        # Not required, but speeds up builds
        githubToken: ${{ github.token }}
        install: |
          apt-get update -q -y
          apt-get install -q -y --no-install-recommends \
                build-essential \
                libgtest-dev \
                ninja-build \
                meson \
                ;
        run: |
          CXXFLAGS=${{ matrix.cxx_flags }} meson setup out -Dwerror=true -Darm7=true
          meson compile -C out -j 2 -v
          meson test -C out -j 2

  aarch64_cmake:
    name: Build and test ${{ matrix.name }} on AArch64
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        include:
          - name: Clang-18
            extra_deps: clang-18
            c_compiler: clang-18
            cxx_compiler: clang++-18
            cxx_standard: 17

          - name: GCC-14
            extra_deps: g++-14
            c_compiler: gcc-14
            cxx_compiler: g++-14
            cxx_flags: -ftrapv
            cxx_standard: 17

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit  # cannot be block - runner does git checkout

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.0.0

      - name: Install deps
        run: sudo apt-get install ninja-build meson ${{ matrix.extra_deps }}

      - name: Configure Build
        run: meson setup out -Dwerror=true -Dcpp_std=c++${{ matrix.cxx_standard }}
        env:
          CXX: ${{matrix.cxx_compiler}}
          CC: ${{matrix.c_compiler}}
          CXXFLAGS: ${{ matrix.cxx_flags }}
      
      - name: Build
        run: meson compile -C out -j 2 -v

      - name: Test
        run: meson test -C out -j 2

  loongarch64_cmake:
    name: Build and test ${{ matrix.name }} on LoongArch64
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - name: GCC-14
            extra_deps: qemu-loongarch64
            cxx_standard: 17
    steps:
      - name: get cross-tools evn
        run: |
          wget https://github.com/loongson/build-tools/releases/download/2025.02.21/x86_64-cross-tools-loongarch64-binutils_2.44-gcc_14.2.0-glibc_2.41.tar.xz
          sudo tar -xvf x86_64-cross-tools-loongarch64-binutils_2.44-gcc_14.2.0-glibc_2.41.tar.xz -C /opt
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit  # cannot be block - runner does git checkout

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.0.0

      - name: Install build requirements
        run: sudo apt-get install ninja-build meson

      - name: Install deps
        run: |
          wget https://github.com/loongson/build-tools/releases/download/2025.02.21/${{ matrix.extra_deps }}
          chmod +x ${{ matrix.extra_deps }}
          sudo mv ${{ matrix.extra_deps }} /opt/cross-tools/bin

      - name: Set environment variables
        run: |
          echo "/opt/cross-tools/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=/opt/cross-tools/loongarch64-unknown-linux-gnu/lib:\$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Create cross file
        run: |
          echo "[binaries]" > la64_cross_file.txt
          echo "c = 'loongarch64-unknown-linux-gnu-gcc'" >> la64_cross_file.txt
          echo "cpp = 'loongarch64-unknown-linux-gnu-g++'" >> la64_cross_file.txt
          echo "ar = 'loongarch64-unknown-linux-gnu-ar'" >> la64_cross_file.txt
          echo "strip = 'loongarch64-unknown-linux-gnu-strip'" >> la64_cross_file.txt
          echo "pkgconfig = 'pkg-config'" >> la64_cross_file.txt
          echo "exe_wrapper = ['qemu-loongarch64','-cpu','max','-L','/opt/cross-tools/target']" >> la64_cross_file.txt
          echo "" >> la64_cross_file.txt
          echo "[host_machine]" >> la64_cross_file.txt
          echo "system = 'linux'" >> la64_cross_file.txt
          echo "cpu_family = 'loongarch64'" >> la64_cross_file.txt
          echo "cpu = 'loongarch64e'" >> la64_cross_file.txt
          echo "endian = 'little'" >> la64_cross_file.txt

      - name: Configure Build
        run: meson setup out --cross-file la64_cross_file.txt -Dwerror=true -Dcpp_std=c++${{ matrix.cxx_standard }}

      - name: Build
        run: meson compile -C out -j 2 -v

      - name: Test
        run: meson test -C out -j 2
