# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

permissions: read-all
name: Meson build / test MacOS and Windows
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  meson_setup_args: -Dwarning_level=2 -Dbuildtype=debugoptimized

jobs:
  meson_win:
    name: Meson build and test ${{ matrix.name }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        include:
          - name: MSVC
            os: windows-2022
            c_compiler: cl
            cxx_compiler: cl
            extra_meson_flags: -Dvsenv=true -Dcontrib=disabled  # MSCV usually chokes on compiling vqsort on CI
            cxx_standard: 17
            cxx_flags: /DHWY_SLOW_MSVC
          
          # windows-11-arm msvc only detects emu128 as a target

            # LLVM is at 20.1.8 on current windows-2022 runner
          - name: LLVM-CL
            os: windows-2022
            c_compiler: clang-cl
            cxx_compiler: clang-cl
            extra_meson_flags: -Dvsenv=true
            cxx_flags: /DHWY_DISABLED_TARGETS=0x58
            cxx_standard: 17
          
          - name: LLVM-CL
            os: windows-11-arm
            c_compiler: clang-cl
            cxx_compiler: clang-cl
            extra_meson_flags: -Dvsenv=true
            cxx_flags: /DHWY_DISABLED_TARGETS=0x58
            cxx_standard: 17

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit  # cannot be block - runner does git checkout

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.0.0

        # update the meson gtest wrap because we're going to use a c++17 standard
      - name: Install deps
        run: |
            pipx install meson

      - name: Configure Build
        run: meson setup out -Dcpp_std=c++${{ matrix.cxx_standard }} ${{env.meson_setup_args}} ${{ matrix.extra_meson_flags }}
        env:
          CXX: ${{matrix.cxx_compiler}}
          CC: ${{matrix.c_compiler}}
          CXXFLAGS: ${{ matrix.cxx_flags }}
          
      - name: Report Targets
        run: |
          meson compile -C out hwy_list_targets
          out\hwy_list_targets

      - name: Build
        run: meson compile -C out -j 2 -v

      - name: Test
        run: meson test -C out -j 2 --print-errorlogs

  meson_macos:
    name: Meson build and test ${{ matrix.name }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [macos-15, macos-13]  # macos-15 is arm, macos-13 is last x86_64 runner
        compiler: [apple, llvm, gnu]
        cxx_standard: [17]
        include:
          - compiler: apple
            name: AppleLLVM
            c_compiler: clang
            cxx_compiler: clang++
            
          - compiler: llvm
            extra_deps: llvm@20 lld@20
            name: LLVM
            c_compiler: $(brew --prefix llvm@20)/bin/clang
            cxx_compiler: $(brew --prefix llvm@20)/bin/clang++
            
          - compiler: gnu
            name: GNU
            extra_deps: gcc@15
            c_compiler: gcc-15
            cxx_compiler: g++-15
          
          - os: macos-13
            # These should probably automatically be excluded on intel-macs... 
            # AVX3 is the highest instruction set for MacPro 2019 (the last for intel-processors).
            cxx_flags: -DHWY_DISABLED_TARGETS='0xd8'
            extra_meson_flags: -Ddisable_futex=true

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit  # cannot be block - runner does git checkout

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.0.0

      - name: Install deps
        run: |
            brew install meson ${{ matrix.extra_deps }}

      - name: Configure Build
        run: |
            export CC=${{ matrix.c_compiler }}
            export CXX=${{ matrix.cxx_compiler }}
            export CXXFLAGS=${{ matrix.cxx_flags }}
            meson setup out -Dcpp_std=c++${{ matrix.cxx_standard }} ${{env.meson_setup_args}} ${{ matrix.extra_meson_flags }}
      
      - name: Report Targets
        run: |
          meson compile -C out hwy_list_targets
          out/hwy_list_targets

      - name: Build
        run: meson compile -C out -j 2 -v

      - name: Test
        run: meson test -C out -j 2 --print-errorlogs