# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

permissions: read-all
name: Meson build / test
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  meson:
    name: Meson build and test ${{ matrix.name }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - name: Clang-11
            extra_deps: clang-11
            c_compiler: clang-11
            cxx_compiler: clang++-11
            cxx_standard: 11

          - name: Clang-12
            extra_deps: clang-12
            c_compiler: clang-12
            cxx_compiler: clang++-12
            cxx_standard: 11

          - name: Clang-13
            extra_deps: clang-13
            c_compiler: clang-13
            cxx_compiler: clang++-13
            cxx_standard: 11

          - name: Clang-14
            extra_deps: clang-14
            c_compiler: clang-14
            cxx_compiler: clang++-14
            cxx_standard: 11

          - name: Clang-15
            extra_deps: clang-15
            c_compiler: clang-15
            cxx_compiler: clang++-15
            cxx_standard: 11

          - name: Clang-15 (C++20)
            extra_deps: clang-15
            c_compiler: clang-15
            cxx_compiler: clang++-15
            cxx_standard: 20

          - name: GCC-9
            extra_deps: g++-9
            c_compiler: gcc-9
            cxx_compiler: g++-9
            cxx_flags: -ftrapv
            cxx_standard: 11

          - name: GCC-10
            extra_deps: g++-10
            c_compiler: gcc-10
            cxx_compiler: g++-10
            cxx_flags: -ftrapv
            cxx_standard: 11

          - name: GCC-11
            extra_deps: g++-11
            c_compiler: gcc-11
            cxx_compiler: g++-11
            cxx_flags: -ftrapv
            cxx_standard: 11

          - name: GCC-11 (C++20)
            extra_deps: g++-11
            c_compiler: gcc-11
            cxx_compiler: g++-11
            cxx_flags: -ftrapv
            cxx_standard: 20

          - name: GCC-12
            extra_deps: g++-12
            c_compiler: gcc-12
            cxx_compiler: g++-12
            cxx_flags: -ftrapv
            cxx_standard: 11

          - name: GCC-12 (C++20)
            extra_deps: g++-12
            c_compiler: gcc-12
            cxx_compiler: g++-12
            cxx_flags: -ftrapv
            cxx_standard: 20

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit  # cannot be block - runner does git checkout

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.0.0

        # meson on jammy is at version 0.61.2, so install through pipx
      - name: Install build requirements
        run: pipx install meson

      - name: Install deps
        run: sudo apt-get install ${{ matrix.extra_deps }}

      - name: Configure Build
        run: meson setup out -Dwerror=true -Dcpp_std=c++${{ matrix.cxx_standard }} -Dreport_targets=true ${{ matrix.extra_mesons_flags }}
        env:
          CXX: ${{matrix.cxx_compiler}}
          CC: ${{matrix.c_compiler}}
          CXXFLAGS: ${{ matrix.cxx_flags }}
      
      - name: Build
        run: meson compile -C out -j 2 -v

      - name: Test
        run: meson test -C out -j 2

  meson_i686:
    name: Meson build and test ${{ matrix.name }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - name: Clang-15 (x86_32)
            extra_deps: clang-15 g++-i686-linux-gnu
            c_compiler: "['clang-15', '--target=i686-linux-gnu']"
            cxx_compiler: "['clang++-15', '--target=i686-linux-gnu']"
            # Disable AVX3 targets on x86_32
            cxx_flags: -m32 -DHWY_DISABLED_TARGETS=0x1FF -DHWY_BROKEN_TARGETS=0x1FF
            cxx_standard: 17

          - name: GCC-12 (x86_32)
            extra_deps: g++-12-i686-linux-gnu
            c_compiler: "'i686-linux-gnu-gcc-12'"
            cxx_compiler: "'i686-linux-gnu-g++-12'"
            # Disable AVX3 targets on x86_32
            cxx_flags: -m32 -ftrapv -DHWY_DISABLED_TARGETS=0x1FF -DHWY_BROKEN_TARGETS=0x1FF
            cxx_standard: 17

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit  # cannot be block - runner does git checkout

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.0.0

      - name: Install build requirements
        run: pipx install meson

      - name: Install deps
        run: sudo apt-get install ${{ matrix.extra_deps }}

      - name: Create cross file
        run: |
          echo "[binaries]" > x86_cross_file.txt
          echo "c = ${{matrix.c_compiler}}" >> x86_cross_file.txt
          echo "cpp = ${{matrix.cxx_compiler}}" >> x86_cross_file.txt
          echo "pkgconfig = 'pkg-config'" >> x86_cross_file.txt
          echo "" >> x86_cross_file.txt
          echo "[host_machine]" >> x86_cross_file.txt
          echo "system = 'linux'" >> x86_cross_file.txt
          echo "cpu_family = 'x86'" >> x86_cross_file.txt
          echo "cpu = 'i686'" >> x86_cross_file.txt
          echo "endian = 'little'" >> x86_cross_file.txt

      - name: Configure Build
        run: meson setup out --cross-file x86_cross_file.txt -Dwerror=true -Dcpp_std=c++${{ matrix.cxx_standard }} -Dsse2=true -Dreport_targets=true
      
      - name: Build
        run: meson compile -C out -j 2 -v

      - name: Test
        run: meson test -C out -j 2

  meson_ubuntu_2404:
    name: Meson build and test ${{ matrix.name }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - name: Clang-16
            extra_deps: clang-16
            c_compiler: clang-16
            cxx_compiler: clang++-16
            # Disable AVX3_SPR/AVX3_ZEN4 targets in GitHub workflow build with
            # Clang 16 or later to work around crashes that occur with Clang 16
            # or later when some of the Google Highway tests are compiled with
            # all x86 targets enabled
            cxx_flags: -DHWY_DISABLED_TARGETS=0x58
            cxx_standard: 17

          - name: Clang-17
            extra_deps: clang-17
            c_compiler: clang-17
            cxx_compiler: clang++-17
            # Disable AVX3_SPR/AVX3_ZEN4 targets in GitHub workflow build with
            # Clang 16 or later to work around crashes that occur with Clang 16
            # or later when some of the Google Highway tests are compiled with
            # all x86 targets enabled
            cxx_flags: -DHWY_DISABLED_TARGETS=0x58
            cxx_standard: 17

          - name: Clang-18
            extra_deps: clang-18
            c_compiler: clang-18
            cxx_compiler: clang++-18
            # Disable AVX3_SPR/AVX3_ZEN4 targets in GitHub workflow build with
            # Clang 16 or later to work around crashes that occur with Clang 16
            # or later when some of the Google Highway tests are compiled with
            # all x86 targets enabled
            cxx_flags: -DHWY_DISABLED_TARGETS=0x58
            cxx_standard: 17

          - name: Clang-18 (C++23)
            extra_deps: clang-18
            c_compiler: clang-18
            cxx_compiler: clang++-18
            # Disable AVX3_SPR/AVX3_ZEN4 targets in GitHub workflow build with
            # Clang 16 or later to work around crashes that occur with Clang 16
            # or later when some of the Google Highway tests are compiled with
            # all x86 targets enabled
            cxx_flags: -DHWY_DISABLED_TARGETS=0x58
            cxx_standard: 23

          - name: GCC-13
            extra_deps: g++-13
            c_compiler: gcc-13
            cxx_compiler: g++-13
            cxx_flags: -ftrapv
            cxx_standard: 17

          - name: GCC-13 (C++23)
            extra_deps: g++-13
            c_compiler: gcc-13
            cxx_compiler: g++-13
            cxx_flags: -ftrapv
            cxx_standard: 23

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit  # cannot be block - runner does git checkout

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.0.0

        # meson on noble is at 1.3.2
      - name: Install deps
        run: sudo apt-get install ninja-build meson ${{ matrix.extra_deps }}

      - name: Configure Build
        run: meson setup out -Dwerror=true -Dcpp_std=c++${{ matrix.cxx_standard }} -Dreport_targets=true
        env:
          CXX: ${{matrix.cxx_compiler}}
          CC: ${{matrix.c_compiler}}
          CXXFLAGS: ${{ matrix.cxx_flags }}
      
      - name: Build
        run: meson compile -C out -j 2 -v

      - name: Test
        run: meson test -C out -j 2